[server.http]
port = 9001
[server.governor]
port = 9003
[mysql.roomx]
connMaxLifetime = "300s"
debug = true
dsn = "root:abcd1234@tcp(localhost:3306)/roomx?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local"
level = "panic"
maxIdleConns = 50
maxOpenConns = 100